spring:
  application:
    name: mall-member
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.6.128:3306/mall-ums
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.6.128:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
        client-ip: localhost
server:
  port: 8043

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

management:
  endpoints:
    web:
      exposure:
        include: '*'
