spring:
  application:
    name: mall-member
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://mysql-master.sangomall.svc.cluster.local.:3306/mall_ums
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: nacos-server.sangomall.svc.cluster.local.:8848
    sentinel:
      transport:
        port: 8719
        dashboard: sentinel-server.sangomall.svc.cluster.local.:8858
        client-ip: localhost
server:
  port: 20300

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

management:
  endpoints:
    web:
      exposure:
        include: '*'
