spring:
  application:
    name: mall-gateway


  cloud:
    nacos:
      discovery:
        server-addr: nacos-server.sangomall.svc.cluster.local.:8848
    sentinel:
      transport:
        port: 8719
        dashboard: sentinel-server.sangomall.svc.cluster.local.:8858
        client-ip: localhost

    gateway:
      routes:
        - id: msbmall_host_route1
          uri: lb://mall-product
          predicates:
            - Host=mall.msb.com

        - id: msbmall_host_route2
          uri: lb://mall-product
          predicates:
            - Host=item.msb.com

        - id: msb_search_host_route
          uri: lb://mall-search
          predicates:
            - Host=search.msb.com

        - id: msb_auth_host_route
          uri: lb://mall-auth-server
          predicates:
            - Host=auth.msb.com

        - id: msbmall_host_route5
          uri: lb://mall-cart
          predicates:
            - Host=cart.msb.com

        - id: msbmall_host_route6
          uri: lb://mall-order
          predicates:
            - Host=order.msb.com

        - id: msbmall_host_route7
          uri: lb://mall-seckill
          predicates:
            - Host=seckill.msb.com



        - id: product_route
          uri: lb://mall-product
          predicates:
            - Path=/app/product/**
          filters:
            - RewritePath=/app/(?<segment>/?.*), /$\{segment}
        - id: coupon_route
          uri: lb://mall-coupon
          predicates:
            - Path=/app/coupon/**
          filters:
            - RewritePath=/app/(?<segment>/?.*), /$\{segment}
        - id: third_route
          uri: lb://mall-third-party
          predicates:
            - Path=/app/third/**
          filters:
            - RewritePath=/app/third/(?<segment>/?.*), /$\{segment}
        - id: member_route
          uri: lb://mall-member
          predicates:
            - Path=/app/member/**
          filters:
            - RewritePath=/app/(?<segment>/?.*), /$\{segment}
        - id: ware_route
          uri: lb://mall-ware
          predicates:
            - Path=/app/ware/**
          filters:
            - RewritePath=/app/(?<segment>/?.*), /$\{segment}
        - id: app_route
          uri: lb://renren-fast
          predicates:
            - Path=/app/**
          filters:
            - RewritePath=/app/(?<segment>/?.*), /renren-fast/$\{segment}




server:
  port: 8072
  address: 0.0.0.0
  tomcat:
    max-threads: 1000 # 最大工作线程（老师的服务肯定调过）
    min-spare-threads: 200
    accept-count: 2000 # 等待队列长度




