spring:
  application:
    name: mall-product
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
    prefix: classpath:/templates
    suffix: .html
  redis:
    host: redis.sangomall.svc.cluster.local.
    port: 6379
    password: 123456
  cache:
    type: redis
    redis:
      time-to-live: 60000
    #  key-prefix: mall_
      use-key-prefix: true
      cache-null-values: true
  session:
    store-type: redis
    redis:
      namespace: spring:session

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://mysql-master.sangomall.svc.cluster.local.:3306/mall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: nacos-server.sangomall.svc.cluster.local.:8848
    alicloud: # 此处为映射块，必须包含缩进的子属性
      access-key: LTAI5tLfmwSFVCmCGYH5YzwS
      secret-key: BuEnOP2vVN01eNjV7L1z9NJA0mXJUP
      oss: # OSS 配置的子节点
        endpoint: oss-cn-shanghai.aliyuncs.com
    sentinel:
      transport:
        port: 8719
        dashboard: sentinel-server.sangomall.svc.cluster.local.:8858
        client-ip: localhost


server:
  port: 8040


mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1h
      logic-not-delete-value: 0

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
feign:
  sentinel:
    enabled: true

