spring:
  application:
    name: mall-search
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  thymeleaf:
    cache: false
    prefix: classpath:/templates
    suffix: .html

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://mysql-master.sangomall.svc.cluster.local.:3306/mall-wms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: nacos-server.sangomall.svc.cluster.local.:8848
    sentinel:
      transport:
        port: 8719
        dashboard: sentinel-server.sangomall.svc.cluster.local.:8858
        client-ip: localhost
  redis:
    host: redis.sangomall.svc.cluster.local.
    port: 6379
    password: 123456
  session:
    store-type: redis
    redis:
      namespace: spring:session

server:
  port: 8090

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

management:
  endpoints:
    web:
      exposure:
        include: '*'
