spring:
  application:
    name: mall-third-party

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.6.128:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
        client-ip: localhost
    alicloud: # 此处为映射块，必须包含缩进的子属性
      access-key: LTAI5tLfmwSFVCmCGYH5YzwS
      secret-key: BuEnOP2vVN01eNjV7L1z9NJA0mXJUP
      oss: # OSS 配置的子节点
        endpoint: oss-cn-shanghai.aliyuncs.com
        bucket: msb-mall-zyh2
      sms:
        host: https://dfsns.market.alicloudapi.com
        path: /data/send_sms
        method: POST
        appCode: 3d8d50a61812496c8b03980ee1d5f77a


server:
  port: 8049

management:
  endpoints:
    web:
      exposure:
        include: '*'


